config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'posts#index'
  resources :users
  resources :posts, only: [:index]
  resources :votes, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :votes
  has_many :upvoted_users, through: :votes, source: :user

  def upvotes
    votes.where(upvote: true).count
  end

  def downvotes
    votes.where(upvote: false).count
  end

  def total_votes
    upvotes - downvotes
  end

end

app/models/user.rb
class User < ApplicationRecord
has_many :votes
has_many :upvoted_posts, through: :votes, source: :post

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # before_save { self.name = name.downcase }
  # validates :name, presence: true, length: { maximum: 55 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id

  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private 

  def logged_in_user
    unless user_signed_in?
      flash[:danger] = "Must be logged in to vote!"
      redirect_to new_user_session_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.sort_by{ |post| post.total_votes }.reverse
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private 

  def sign_up_params 
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order(created_at: :desc).all
  end
  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :logged_in_user, only: [:create] 

  def create
    @post = Post.find(vote_params[:post_id])
    @vote = current_user.votes.find_or_initialize_by(post_id: @post.id)
    if @vote.upvote.to_s == vote_params[:upvote]
      if @vote.destroy
        @destroy = true
      end
    else
      @vote.upvote = vote_params[:upvote]
      if @vote.save
        @success = true
      end
    end
  end

  private
  
  def vote_params
    params.require(:vote).permit(:post_id, :upvote)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def voted_on?(post)
    return unless current_user
    return 'voted_on' if current_user.votes.where(post_id: post.id).first.present?
  end

  def voted_class(post, vote_type)
    return unless current_user
    vote = current_user.votes.where(post_id: post.id).first


    if vote.present?
      if vote.upvote? && vote_type == :upvote
        ' clicked_btn'
      elsif !vote.upvote? && vote_type == :downvote
        ' clicked_btn'
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_header.html.erb
<div class="head-box">
  <ul class="header">
    <li><%= link_to "Images", root_path, {style: 'color:#fff;'} %></li>
    <li><%= link_to "Users",  users_path, {style: 'color:#fff;'} %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Logout", destroy_user_session_path, {method: :delete, style: 'color:#fff;'} %></li>
    <% else %>
      <li><%= link_to "Login", new_user_session_path, {style: 'color:#fff;'} %></li>
      <li><%= link_to "Sign Up", new_user_registration_path, {style: 'color:#fff;'} %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicvoteApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
    <div class="box">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="img_box <%= voted_on?(post) %>" id="post_<%= post.id %>" >
  <%= image_tag "/assets/post_images/#{post.image_name}", class:"img_preview" %>
  <div class="total_votes">Post Score: <%= post.total_votes %></div>

  <%= button_to votes_path(vote: { post_id: post.id , upvote: true }), method: :post, remote: true, class: "vote_btn upvote #{voted_class(post, :upvote)}" do
  %>
  <i class="fa fa-arrow-up" aria-hidden="true" style="font-size:22px;"></i>
  <% end %>

  <%= button_to votes_path(vote: { post_id: post.id , upvote: false }), method: :post, remote: true, class: "vote_btn downvote #{voted_class(post, :downvote)}" do
  %>
  <i class="fa fa-arrow-down" aria-hidden="true" style="font-size:22px;"></i>
    
  <% end %>
</div>

app/views/posts/index.html.erb
<title>Picvote</title>
    <%= render @posts %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<title>Users</title>

<h1>Picvote Users</h1>

<ul class="users">
  <% @users.each do |user| %>
  <li>
    <b>Name:</b> <%= user.name %>,
    <b>Created on:</b> <%= user.created_at.strftime("%a, %B, %d, %Y at %I:%M%p") %>
  </li>
  <% end %>
</ul>

app/views/votes/create.js.erb
<% if @success %>
  <% if @vote.upvote %>
    update_vote('.upvote');
  <% else %>
    update_vote('.downvote');
  <% end %>
<% elsif @destroy %>
  update_vote(false)
<% else %>
  console.log("UH OH! Try again!")
<% end %>

function update_vote(btn_class) {
  post_id = '#post_' + <%= @post.id %>
  
    $( post_id + ' .vote_btn').removeClass('clicked_btn');
    $( post_id + '.img_box').removeClass('voted_on');
    $( post_id + ' .total_votes').html('New Score: ' + <%= @post.total_votes %>)

    if (btn_class != false) {
      $( post_id + '.img_box').addClass('voted_on')
      $( post_id + ' ' + btn_class).addClass('clicked_btn');
    }
}